/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 334013489
 */
public class PromotionGraphics extends javax.swing.JFrame {

    int xAxis, yAxis, pawn;
    boolean colour;
    /**
     * Creates new form PromotionGraphics
     * @param x
     * @param y
     * @param color
     */
    public PromotionGraphics(int indexOfPawn, int x, int y, boolean color) {
        xAxis = x;
        yAxis = y;
        colour = color;
        pawn = indexOfPawn;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnRook = new javax.swing.JButton();
        btnKnight = new javax.swing.JButton();
        btnBishop = new javax.swing.JButton();
        btnQueen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Promotion Graphics (1).jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnRook.setText("Rook");
        btnRook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRookActionPerformed(evt);
            }
        });
        getContentPane().add(btnRook, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 270, 80));

        btnKnight.setText("Knight");
        btnKnight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKnightActionPerformed(evt);
            }
        });
        getContentPane().add(btnKnight, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 240, 80));

        btnBishop.setText("Bishop");
        btnBishop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBishopActionPerformed(evt);
            }
        });
        getContentPane().add(btnBishop, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 260, 80));

        btnQueen.setText("Queen");
        btnQueen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQueenActionPerformed(evt);
            }
        });
        getContentPane().add(btnQueen, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 240, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRookActionPerformed
        // TODO add your handling code here:
        PromotionChange("rook");
        dispose();
    }//GEN-LAST:event_btnRookActionPerformed

    private void btnKnightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKnightActionPerformed
        // TODO add your handling code here:
        PromotionChange("knight");
        dispose();
    }//GEN-LAST:event_btnKnightActionPerformed

    private void btnBishopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBishopActionPerformed
        // TODO add your handling code here:
        PromotionChange("bishop");
        dispose();
    }//GEN-LAST:event_btnBishopActionPerformed

    private void btnQueenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQueenActionPerformed
        // TODO add your handling code here:
        dispose();
        PromotionChange("queen");
        
    }//GEN-LAST:event_btnQueenActionPerformed

    public void PromotionChange(String changeType){
        Chess1 promote = new Chess1();
        promote.PromotionChange(pawn, xAxis, yAxis, changeType);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBishop;
    private javax.swing.JButton btnKnight;
    private javax.swing.JButton btnQueen;
    private javax.swing.JButton btnRook;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}