/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 334013489
 */
public class PromotionGraphics extends javax.swing.JFrame {

    int pawn, xAxis, yAxis;
    boolean colour;
    /**
     * Creates new form PromotionGraphics
     */
    public PromotionGraphics(int pawnArrayIndex, int x, int y, boolean color) {
        pawn = pawnArrayIndex;
        xAxis = x;
        yAxis = y;
        colour = color;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnRook = new javax.swing.JButton();
        btnKnight = new javax.swing.JButton();
        btnBishop = new javax.swing.JButton();
        btnQueen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Promotion Graphics (1).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnRook.setText("Rook");
        btnRook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRookActionPerformed(evt);
            }
        });
        getContentPane().add(btnRook, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 250, 80));

        btnKnight.setText("Knight");
        btnKnight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKnightActionPerformed(evt);
            }
        });
        getContentPane().add(btnKnight, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 240, 80));

        btnBishop.setText("Bishop");
        btnBishop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBishopActionPerformed(evt);
            }
        });
        getContentPane().add(btnBishop, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 250, 80));

        btnQueen.setText("Queen");
        btnQueen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQueenActionPerformed(evt);
            }
        });
        getContentPane().add(btnQueen, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 260, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRookActionPerformed
        // TODO add your handling code here:
        dispose();
        PromotionChange("rook");
    }//GEN-LAST:event_btnRookActionPerformed

    private void btnKnightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKnightActionPerformed
        // TODO add your handling code here:
        dispose();
        PromotionChange("knight");
    }//GEN-LAST:event_btnKnightActionPerformed

    private void btnBishopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBishopActionPerformed
        // TODO add your handling code here:
        dispose();
        PromotionChange("bishop");
    }//GEN-LAST:event_btnBishopActionPerformed

    private void btnQueenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQueenActionPerformed
        // TODO add your handling code here:
        dispose();
        PromotionChange("queen");
    }//GEN-LAST:event_btnQueenActionPerformed
    
    public void PromotionChange(String changeType){
        Chess1 promote = new Chess1();
        promote.PromotionChange(pawn, xAxis, yAxis, changeType);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBishop;
    private javax.swing.JButton btnKnight;
    private javax.swing.JButton btnQueen;
    private javax.swing.JButton btnRook;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
