/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.ImageIcon;
/**
 *
 * @author 334013489
 */
public class HowToPlay extends javax.swing.JFrame {

    int chessRulePage = 1;
    int appTutorialPage = 1;
    boolean whichTutorial;
    
    ImageIcon intro = new ImageIcon("How to Play Chess Rules.jpg");
    ImageIcon capturing = new ImageIcon("How to Play Capturing.jpg");
    ImageIcon rook = new ImageIcon("How to Play Rook.jpg");
    ImageIcon knight = new ImageIcon("How to Play Knight.jpg");
    ImageIcon bishop = new ImageIcon("How to Play Bishop.jpg");
    ImageIcon queen = new ImageIcon("How to Play Queen.jpg");
    ImageIcon king = new ImageIcon("How to Play King.jpg");
    ImageIcon pawn = new ImageIcon("How to Play Pawn.jpg");
    ImageIcon castling = new ImageIcon("How to Play Castling.jpg");
    
    /**
     * Creates new form HowToPlay
     */
    public HowToPlay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnAppTutorial = new javax.swing.JButton();
        btnChessRules = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPage.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(labelPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 800, 450));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/How to Play Base.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 170, 60));

        btnAppTutorial.setText("App Tutorial");
        btnAppTutorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppTutorialActionPerformed(evt);
            }
        });
        getContentPane().add(btnAppTutorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 350, 60));

        btnChessRules.setText("Chess Rules");
        btnChessRules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChessRulesActionPerformed(evt);
            }
        });
        getContentPane().add(btnChessRules, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 350, 60));

        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 710, 50, 50));

        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 710, 50, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAppTutorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppTutorialActionPerformed
        // TODO add your handling code here:
        whichTutorial = true;
    }//GEN-LAST:event_btnAppTutorialActionPerformed

    private void btnChessRulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChessRulesActionPerformed
        // TODO add your handling code here:
        whichTutorial = false;
        labelPage.setIcon(intro);
    }//GEN-LAST:event_btnChessRulesActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        if(whichTutorial == true){
            appTutorialPage++;
            DisplayTutorialPageApp();
        }
        if(whichTutorial == false && chessRulePage < 9){
            chessRulePage++;
            DisplayTutorialPageChess();
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
        if(whichTutorial == true && appTutorialPage > 1){
            appTutorialPage--;
            DisplayTutorialPageApp();
        }
        if(whichTutorial == false && chessRulePage > 1){
            chessRulePage--;
            DisplayTutorialPageChess();
        }
    }//GEN-LAST:event_btnPreviousActionPerformed

    public void DisplayTutorialPageApp(){
        
    }
    
    public void DisplayTutorialPageChess(){
        if(chessRulePage == 1){
            labelPage.setIcon(intro);
        }
        if(chessRulePage == 2){
            labelPage.setIcon(capturing);
        }
        if(chessRulePage == 3){
            labelPage.setIcon(rook);
        }
        if(chessRulePage == 4){
            labelPage.setIcon(knight);
        }
        if(chessRulePage == 5){
            labelPage.setIcon(bishop);
        }
        if(chessRulePage == 6){
            labelPage.setIcon(queen);
        }
        if(chessRulePage == 7){
            labelPage.setIcon(king);
        }
        if(chessRulePage == 8){
            labelPage.setIcon(pawn);
        }
        if(chessRulePage == 9){
            labelPage.setIcon(castling);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAppTutorial;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnChessRules;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelPage;
    // End of variables declaration//GEN-END:variables
}
