/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 334013489
 */
public class PlayerName extends javax.swing.JFrame {
    /**
     * Creates new form PlayerName
     */
    public PlayerName() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtWhiteSideName = new javax.swing.JTextField();
        txtBlackSideName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnEnter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtWhiteSideName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 570, 50));
        getContentPane().add(txtBlackSideName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 570, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Player Name.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 410));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 150, 40));

        btnEnter.setText("Enter");
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 70, 160, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new TitlePage().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        if (txtWhiteSideName.getText().equals("") || txtBlackSideName.getText().equals("")) {
            if (txtWhiteSideName.getText().equals("")) {
                txtWhiteSideName.setText("--Error: Please enter a username");
            }
            
            if (txtBlackSideName.getText().equals("")) {
                txtBlackSideName.setText("--Error: Please enter a username");
            }
            
            return;
        }
        
        Chess mainBoard = new Chess(this);
        mainBoard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEnterActionPerformed
   
    public String WhiteSideName(){
        return txtWhiteSideName.getText();
    }
    
    public String BlackSideName(){
        return txtBlackSideName.getText();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    public javax.swing.JButton btnEnter;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtBlackSideName;
    private javax.swing.JTextField txtWhiteSideName;
    // End of variables declaration//GEN-END:variables
}
