/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 334013489
 */
public class PromotionGraphics extends javax.swing.JFrame {

    private Piece promotedPawn;
    private Chess chess;
    
    /**
     * Creates new form PromotionGraphics
     */
    public PromotionGraphics(Chess chess, Piece promotedPawn) {
        this.chess = chess;
        this.promotedPawn = promotedPawn;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnRook = new javax.swing.JButton();
        btnKnight = new javax.swing.JButton();
        btnBishop = new javax.swing.JButton();
        btnQueen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Promotion Graphics (1).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, -1));

        btnRook.setText("Rook");
        btnRook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRookActionPerformed(evt);
            }
        });
        getContentPane().add(btnRook, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 240, 80));

        btnKnight.setText("Knight");
        btnKnight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKnightActionPerformed(evt);
            }
        });
        getContentPane().add(btnKnight, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 250, 80));

        btnBishop.setText("Bishop");
        btnBishop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBishopActionPerformed(evt);
            }
        });
        getContentPane().add(btnBishop, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 260, 80));

        btnQueen.setText("Queen");
        btnQueen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQueenActionPerformed(evt);
            }
        });
        getContentPane().add(btnQueen, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 250, 80));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRookActionPerformed
        promotionChange("rook");
    }//GEN-LAST:event_btnRookActionPerformed

    private void btnBishopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBishopActionPerformed
        promotionChange("bishop");
    }//GEN-LAST:event_btnBishopActionPerformed

    private void btnKnightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKnightActionPerformed
        promotionChange("knight");
    }//GEN-LAST:event_btnKnightActionPerformed

    private void btnQueenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQueenActionPerformed
        promotionChange("queen");
    }//GEN-LAST:event_btnQueenActionPerformed
    
    public void promotionChange(String promotionTo){    
        if (promotedPawn.getIsWhite()) {
            chess.whitePlayer.remove(promotedPawn);
            
            if (promotionTo.equals("rook")) {
                chess.whitePlayer.add(new Rook(promotedPawn.getX(), 8, true, chess.whiteRook));
            } else if (promotionTo.equals("knight")) {
                chess.whitePlayer.add(new Knight(promotedPawn.getX(), 8, true, chess.whiteKnight));
            } else if (promotionTo.equals("bishop")) {
                chess.whitePlayer.add(new Bishop(promotedPawn.getX(), 8, true, chess.whiteBishop));
            } else if (promotionTo.equals("queen")) {
                chess.whitePlayer.add(new Queen(promotedPawn.getX(), 8, true, chess.whiteQueen));
            }
        } else {
            chess.blackPlayer.remove(promotedPawn);
            
            if (promotionTo.equals("rook")) {
                chess.blackPlayer.add(new Rook(promotedPawn.getX(), 1, false, chess.blackRook));
            } else if (promotionTo.equals("knight")) {
                chess.blackPlayer.add(new Knight(promotedPawn.getX(), 1, false, chess.blackKnight));
            } else if (promotionTo.equals("bishop")) {
                chess.blackPlayer.add(new Bishop(promotedPawn.getX(), 1, false, chess.blackBishop));
            } else if (promotionTo.equals("queen")) {
                chess.blackPlayer.add(new Queen(promotedPawn.getX(), 1, false, chess.blackQueen));
            }
        }
        
        chess.updateBoard();
        this.dispose();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBishop;
    private javax.swing.JButton btnKnight;
    private javax.swing.JButton btnQueen;
    private javax.swing.JButton btnRook;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
